Update how-to-extend-otrs.rst
znuny/manual pull request #7
Opened 2024-09-20 08:11 UTC by MIPMHannes

This example is broken because `1;` is ignored

2024-10-23 11:57 UTC, dennykorsukewitz requested changes
Hi  @MIPMHannes ,
thanks for your PR.

I have a few change requests here.

`=cut` is missing...

Regards :rocket:

2024-10-23 11:57 UTC, dennykorsukewitz commented on source/developer/contributing/how-to-extend-otrs.rst
```suggestion
   
    =end Internal:

    =cut
    
     1;
```

2024-10-23 11:59 UTC, dennykorsukewitz commented
Hi @MIPMHannes 

can you please verify the changes.

Thanks.

2024-10-23 12:24 UTC, MIPMHannes reviewed
You are right. I think this is the correct way

2024-11-01 10:16 UTC, rkaldung approved these changes

2024-11-01 10:17 UTC, merged